Add more test for deque.
moonbitlang/core pull request #1385
Opened 2024-12-29 13:31 UTC by SyoujyoujiNaiki

Related issue #1363

2024-12-30 01:53 UTC, Lampese commented
Is there any problem with the ubuntu-latest CI?

2024-12-30 02:36 UTC, peter-jerry-ye requested changes
It would be better if the coverage can be raised. To trigger those `guard`, you can `break` inside a `for .. in` loop.

Also please avoid using meme numbers. If possible, please use 0, 1, 2, 3, 12345, 10000, etc., or min/max of Int instead.

2024-12-30 15:32 UTC, SyoujyoujiNaiki commented
> To trigger those `guard`, you can `break` inside a `for .. in` loop.

I don't really know what that means.

2024-12-31 02:09 UTC, peter-jerry-ye commented
> > To trigger those `guard`, you can `break` inside a `for .. in` loop.
> 
> I don't really know what that means.

Ok, here's the thing. When you are constructing an `Iter`, there's two state after a value is consumed: `IterContinue` or `IterBreak`.

The `IterBreak` comes from :

```moonbit
for i in [1, 2, 3] {
  if i == 2 {
      break // <- here
  }
}
```

And when we receive the signal, we as the developer of `Iter`, know that the iteration is done, so we break. That's why you'll see:

```moonbit
guard let yield_(value) == IterContinue else { x => return x } // <- here
```

So here's a little example:

```moonbit
///|
fn iter_array[T : Show](array : Array[T]) -> Iter[T] {
  Iter::new(fn(yield_) {
    for i = 0; i < array.length(); i = i + 1 {
      guard let IterContinue = yield_(array[i]) else {
        IterEnd => {
          println(array[i])
          return IterEnd
        }
      }

    } else {
      IterContinue
    }
  })
}

///|
fn main {
  for i in iter_array([1, 2, 3, 4, 5]) {
    if i == 3 {
      break
    }
  }
}
```

The previous code should print "3".

In the case of `deque`, there are a [lot of lines missing coverage](https://coveralls.io/builds/71521186/source?filename=deque%2Fdeque.mbt#L625), so I would like you to try to come up with some data that will allow it to break in the `for .. in` loop so that the `guard let` statements get tested.

2025-01-02 01:55 UTC, peter-jerry-ye approved these changes

2025-01-02 01:57 UTC, peter-jerry-ye commented
Thanks for the PR

2025-01-02 01:59 UTC, merged