improve coverages
moonbitlang/core pull request #586
Opened 2024-06-21 06:25 UTC by tonyfettes

1. changes all abort to panic for testing.
2. add more test to improve coverages.

2024-06-21 06:46 UTC, tonyfettes commented on builtin/bytes.mbt
> +  } else if code < 0x110000 {
added a bound check here.

2024-06-21 06:51 UTC, tonyfettes commented
Most tests are written by AI and I had to manually modified the generated test cases at least 90% of the cases. Surprisingly it do improve the coverage a little bit.

2024-06-25 01:49 UTC, bobzhang requested changes
can you reduce the changes on the lib itself based on #595

2024-06-25 03:30 UTC, bobzhang approved these changes

2024-06-25 03:30 UTC, merged